"""Fire type and fire size helpers.

Fire/smoke/final scene status are now handled by:
- core/fire_decision_engine.py
- core/smoke_decision_engine.py
- core/scene_decision_engine.py
"""

from typing import Dict, List, Tuple

from src import config
from src.core.geometry import box_area, choose_reference_object


def infer_fire_type(final_fire_status: str, clip_type_result: Dict, detections: List[Dict], flame_region: Dict) -> Tuple[str, str]:
    if final_fire_status != "Fire":
        return "None", "no_fire"

    clip_type = clip_type_result.get("label", "None")
    clip_scores = clip_type_result.get("scores", {}) or {}
    fire_box = flame_region.get("union_box")
    ref = choose_reference_object(fire_box, detections)
    object_names = {d["class_name"] for d in detections}

    if ref is not None and ref["class_name"] in config.VEHICLE_CLASSES:
        if ref.get("overlap_ratio", 0.0) >= 0.03 or ref.get("center_distance", 999999.0) < 220:
            return "Vehicle Fire", f"fire_region_near_or_overlaps_{ref['class_name']}"
    if object_names & config.VEHICLE_CLASSES and float(flame_region.get("image_percent", 0.0)) >= 0.08:
        return "Vehicle Fire", "large_flame_region_with_vehicle_detected"

    if clip_type == "Container / Trash Fire":
        if clip_scores.get("Container / Trash Fire", 0.0) >= 0.40 and not (object_names & config.VEHICLE_CLASSES):
            return "Container / Trash Fire", "strong_clip_container_no_vehicle"
        best_non_container = max(
            {k: v for k, v in clip_scores.items() if k != "Container / Trash Fire"}.items(),
            key=lambda item: item[1],
        )[0]
        return best_non_container, "container_downgraded_to_next_best_context"

    if clip_scores.get(clip_type, 0.0) >= config.CLIP_CONTEXT_THRESHOLD:
        return clip_type, "clip_context"
    return "Other Fire", "low_context_confidence"


def estimate_fire_size(final_fire_status: str, image, flame_region: Dict, detections: List[Dict]) -> Dict:
    if final_fire_status != "Fire":
        return {"size": "None", "method": "no_visible_fire", "reference_object": "None", "ratio": 0.0, "fire_image_percent": 0.0}
    if image is None:
        return {"size": "Unknown", "method": "no_image", "reference_object": "None", "ratio": 0.0, "fire_image_percent": 0.0}

    fire_box = flame_region.get("union_box")
    fire_area = float(flame_region.get("area", 0.0))
    fire_pct = float(flame_region.get("image_percent", 0.0))
    if fire_box is None or fire_area <= 0:
        return {"size": "Unknown / No Flame Region Found", "method": "classifier_only_no_fire_box", "reference_object": "None", "ratio": 0.0, "fire_image_percent": round(fire_pct, 4)}

    ref = choose_reference_object(fire_box, detections)
    if ref is not None:
        ref_area = box_area(ref["box"])
        ratio = fire_area / ref_area if ref_area > 0 else 0.0
        if ratio < 0.10:
            size = "Small Relative Fire"
        elif ratio < 0.40:
            size = "Medium Relative Fire"
        elif ratio < 0.90:
            size = "Large Relative Fire"
        else:
            size = "Fully Involved / Very Large Relative Fire"
        if ref["class_name"] in config.VEHICLE_CLASSES and (ratio >= 0.35 or ref.get("overlap_ratio", 0.0) >= 0.20):
            size = "Large / Fully Involved Vehicle Fire"
        return {"size": size, "method": "relative_to_detected_object", "reference_object": ref["class_name"], "ratio": round(ratio, 3), "fire_image_percent": round(fire_pct, 4)}

    if fire_pct < 0.03:
        size = "Small Fire (image-percent fallback)"
    elif fire_pct < 0.15:
        size = "Medium Fire (image-percent fallback)"
    elif fire_pct < 0.35:
        size = "Large Fire (image-percent fallback)"
    else:
        size = "Very Large Fire (image-percent fallback)"
    return {"size": size, "method": "image_percent_fallback", "reference_object": "None", "ratio": 0.0, "fire_image_percent": round(fire_pct, 4)}


def classify_scene(final_fire_status: str, final_fire_type: str, object_names: List[str]) -> str:
    # Deprecated compatibility helper. The active scene label is generated by
    # core/scene_decision_engine.py. If fire is present, return the fire type.
    if final_fire_status == "Fire" and final_fire_type not in {"", "None", "Unknown"}:
        return final_fire_type
    if final_fire_status == "Fire":
        return "Fire"
    if any(name in config.VEHICLE_CLASSES for name in object_names):
        return "Vehicle / Accident Scene"
    if final_fire_status == "Uncertain":
        return "Uncertain Fire Scene"
    return "No Fire / Unknown Scene"
